import io.reactivex.Observable;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        String[] str = {"hello Rx","one","two","three","four"};
        Observable.just(str)
        .subscribe( line -> {
          for ( int i = 0; i < line.length ; i++) {
            System.out.println(line[i]);
          }
        } );
    }
}
